### ISSUE TITLE
Enable the pass-through of a verify parameter to httpx

### ISSUE THREAD

**Issue by jgerhard7** [FOLIO-FSE/FolioClient#20]
Our library is now requiring self-signed certificates for SSL usage. How can we pass through a verify parameter to folioclient?

With requests I've been able to use a solution like [this one](https://stackoverflow.com/a/30405947): `r = requests.post(url, data=data, verify='/path/to/public_key.pem')`

It looks like httpx will also allow a verify param.

But I tried the following:

`fc = folioclient.FolioClient(url, tenant_id, username, password, verify=False)`

and got the TypeError:
`FolioClient.__init__() got an unexpected keyword argument 'verify'`

I could try to submit a PR if I can figure it out on my end.

**Comment by bltravis** [comment]
@jgerhard7 Can you give https://github.com/FOLIO-FSE/FolioClient/tree/20-enable-the-pass-through-of-a-verify-parameter-to-httpx a try. It accepts an optional "ssl_verify" argument that you can pass the same values to as `verify` in an `httpx.Client` object or method. If this works for you, I'll merge and try to get a minor version release out that includes this fix.
