### ISSUE TITLE
Invalid URLs if okapi_url has a path component

### ISSUE THREAD

**Issue by kt-bvb** [FOLIO-FSE/FolioClient#67]
The changed URL handling introduced in #52 (where f-strings were replaced with `urljoin` to concatenate the okapi_url with the required API endpoint) results in invalid URLS if the okapi_url has a path component.

```
>>> urllib.parse.urljoin("https://www.example.org/path/to/okapi", "/authn/login-with-expiry")
'https://www.example.org/authn/login-with-expiry'
```

Since the path component from the okapi_url is ommited from the new (incorrect) URLs, login and the other methods fail.

**Comment by bltravis** [comment]
Fixed by #69
